// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiT-CffjQqdxqKuexjeDv-SUMnJQ-02mc',
    appId: '1:147762889057:web:52903077448131ef380520',
    messagingSenderId: '147762889057',
    projectId: 'medicines-32824',
    authDomain: 'medicines-32824.firebaseapp.com',
    storageBucket: 'medicines-32824.firebasestorage.app',
    measurementId: 'G-QBC7YWQN3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpQUsVB-J_wLmjruWh_WXMV57_7SvahV0',
    appId: '1:147762889057:android:1ea8eaf060d45e68380520',
    messagingSenderId: '147762889057',
    projectId: 'medicines-32824',
    storageBucket: 'medicines-32824.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLFKXeZNz5-0UOvtIjjYrwOlryI-_rY6g',
    appId: '1:147762889057:ios:76f4107b59e6885f380520',
    messagingSenderId: '147762889057',
    projectId: 'medicines-32824',
    storageBucket: 'medicines-32824.firebasestorage.app',
    iosBundleId: 'com.example.healthCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLFKXeZNz5-0UOvtIjjYrwOlryI-_rY6g',
    appId: '1:147762889057:ios:76f4107b59e6885f380520',
    messagingSenderId: '147762889057',
    projectId: 'medicines-32824',
    storageBucket: 'medicines-32824.firebasestorage.app',
    iosBundleId: 'com.example.healthCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiT-CffjQqdxqKuexjeDv-SUMnJQ-02mc',
    appId: '1:147762889057:web:c7ee8f7c0ac419bc380520',
    messagingSenderId: '147762889057',
    projectId: 'medicines-32824',
    authDomain: 'medicines-32824.firebaseapp.com',
    storageBucket: 'medicines-32824.firebasestorage.app',
    measurementId: 'G-FKWBP3QDBB',
  );
}
